app/apis/webapi/wp/get.application.details.php, app/modules/subs/payment.php
Task : Application ID not generated properly
=> Application ID not generated properly

app/config/constants.php, app/plugins/leadsquared/loadplugin.php, app/tasks/leads.compile.php
Lead square new account integration- dev completed
=> Dev lead square

app/modules/subs/package.php, app/modules/subs/subs.php, app/templates/email/payment/init.php, app/templates/jaws/backend/dash/assets/js/controllers/payment.edit.js, dbmigration/JA-54-package_add_new_column.sql
=> JA-54 email and bacave rectification

app/apis/webapi/backend/dash/package.export.php
Changing all the datetime format to d-M-y H:i:s in track payments download report
=> JA-103 fixe

app/apis/webapi/backend/dash/package.export.php
date tiem format change in download payment report
=> JA-103 released to prod

app/config/email.php
Sendgrid email credentials remvoed
=> JA-106  email keys removed - sendgrid

app/apis/webapi/user.call.php, app/templates/jaws/backend/dash/assets/js/controllers/home.js, app/templates/jaws/backend/dash/tpl/home.html
=> Dev ja 109

app/templates/email/payment/platforms/edunxt/init.php
=> JA-91 fixed

app/apis/webapi/backend/dash/lsdashboard.php, app/templates/jaws/backend/dash/assets/js/config.js, app/templates/jaws/backend/dash/assets/js/controllers/ls.dashboard.js, app/templates/jaws/backend/dash/pages/css/pages.css, app/templates/jaws/backend/dash/tpl/blocks/sidebar.html, app/templates/jaws/backend/dash/tpl/home.html, app/templates/jaws/backend/dash/tpl/ls.dashboard.html
=> JA-113 Ls Dashboard

app/templates/jaws/backend/dash/assets/js/controllers/ls.dashboard.js
Feedback Changes On LS Dashboard
=> Feedback Changes On LS Dashboard

app/libraries/db.php, app/templates/jaws/backend/dash/assets/js/controllers/payment.track.js, app/templates/jaws/backend/dash/assets/js/main.js, app/templates/jaws/backend/dash/tpl/payment.track.html
=> Dev uifix 120

app/apis/webapi/backend/dash/lsdashboard.php, app/plugins/leadsquared/loadplugin.php, app/templates/jaws/backend/dash/assets/js/controllers/ls.dashboard.js, app/templates/jaws/backend/dash/pages/css/pages.css, app/templates/jaws/backend/dash/tpl/blocks/sidebar.html, app/templates/jaws/backend/dash/tpl/home.html, app/templates/jaws/backend/dash/tpl/ls.dashboard.html
Releasing LS Dashboard version1
=> release ls dashboard  to prod

app/modules/leads/basic.php, app/plugins/leadsquared/loadplugin.php
Fixed: PRoduction issue Lead compile updateleadstatus not working
=> production lead compile err - updateleadstatus

app/templates/jaws/backend/dash/assets/js/config.js, app/templates/jaws/backend/dash/assets/js/controllers/ls.dashboard.js, app/templates/jaws/backend/dash/pages/css/pages.css, app/templates/jaws/backend/dash/tpl/ls.dashboard.html, app/templates/jaws/backend/dash/tpl/pagination.html
Date Filter and pagination implemented.
=> Date Filter and Pagination Done

app/templates/jaws/backend/dash/tpl/blocks/sidebar.html, dbmigration/JA-145-new-role-ls-dashboard.sql
Release new role for LS Dashboard
=> Release Branch for LS Dashboard

app/config/payment.php, app/libraries/db.php, app/plugins/razorpay/loadplugin.php, app/templates/jaws/frontend/pg.select.php, app/views/frontend/payment/paylink.parse.php
Releasing new razorpay account
=> Release new razor pay account

app/config/leadsqaure.php, app/modules/leads/leadcommon.php, app/tasks/leads/basic2compile.php, app/tasks/leads/compiled2leadsquare.php
Production Deploy : Fix for leads not pushed to New LS account
=> Fix for leads not pushed to New LS account

.gitignore, app/tasks/leads/compiled2leadsquare.php, app/templates/email/corporate/corporate_lead.php, dbmigration/TK064-corporate-lead-email.sql
added functionality for send email for corporate lead.
=> Dev k tk064

app/templates/jaws/backend/dash/assets/js/config.js, app/templates/jaws/backend/dash/assets/js/controllers/payment.edit.js, app/templates/jaws/backend/dash/assets/js/controllers/payment.track.js, app/templates/jaws/backend/dash/tpl/payment.edit.html
K-form date update while slider day change
=> K-form Slider Days Changes

app/tasks/leads/compiled2leadsquare.php, app/templates/email/corporate/corporate_lead.php, dbmigration/TK064-corporate-lead-email.sql
- app/templates/email/corporate/corporate_lead.php -> corporate email template.
- app/tasks/leads/compiled2leadsquare.php -> add check for the lead is corporate then send email to predefined emails
- dbmigration/TK064-corporate-lead-email.sql -> insert query for email template & the email ids to send email.
=> TK064 Release changes
